// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package room

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RoomClient is the client API for Room service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomClient interface {
	Get(ctx context.Context, in *RoomGetRequest, opts ...grpc.CallOption) (*RoomGetResponse, error)
	GetByUserID(ctx context.Context, in *RoomGetByUserIDRequest, opts ...grpc.CallOption) (*RoomGetByUserIDResponse, error)
	GetUsers(ctx context.Context, in *RoomGetUsersRequest, opts ...grpc.CallOption) (*RoomGetUsersResponse, error)
	Create(ctx context.Context, in *RoomCreateRequest, opts ...grpc.CallOption) (*RoomCreateResponse, error)
	AddUser(ctx context.Context, in *RoomAddUserRequest, opts ...grpc.CallOption) (*RoomAddUserResponse, error)
}

type roomClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomClient(cc grpc.ClientConnInterface) RoomClient {
	return &roomClient{cc}
}

func (c *roomClient) Get(ctx context.Context, in *RoomGetRequest, opts ...grpc.CallOption) (*RoomGetResponse, error) {
	out := new(RoomGetResponse)
	err := c.cc.Invoke(ctx, "/shinfo.room.Room/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) GetByUserID(ctx context.Context, in *RoomGetByUserIDRequest, opts ...grpc.CallOption) (*RoomGetByUserIDResponse, error) {
	out := new(RoomGetByUserIDResponse)
	err := c.cc.Invoke(ctx, "/shinfo.room.Room/GetByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) GetUsers(ctx context.Context, in *RoomGetUsersRequest, opts ...grpc.CallOption) (*RoomGetUsersResponse, error) {
	out := new(RoomGetUsersResponse)
	err := c.cc.Invoke(ctx, "/shinfo.room.Room/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) Create(ctx context.Context, in *RoomCreateRequest, opts ...grpc.CallOption) (*RoomCreateResponse, error) {
	out := new(RoomCreateResponse)
	err := c.cc.Invoke(ctx, "/shinfo.room.Room/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) AddUser(ctx context.Context, in *RoomAddUserRequest, opts ...grpc.CallOption) (*RoomAddUserResponse, error) {
	out := new(RoomAddUserResponse)
	err := c.cc.Invoke(ctx, "/shinfo.room.Room/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServer is the server API for Room service.
// All implementations must embed UnimplementedRoomServer
// for forward compatibility
type RoomServer interface {
	Get(context.Context, *RoomGetRequest) (*RoomGetResponse, error)
	GetByUserID(context.Context, *RoomGetByUserIDRequest) (*RoomGetByUserIDResponse, error)
	GetUsers(context.Context, *RoomGetUsersRequest) (*RoomGetUsersResponse, error)
	Create(context.Context, *RoomCreateRequest) (*RoomCreateResponse, error)
	AddUser(context.Context, *RoomAddUserRequest) (*RoomAddUserResponse, error)
	mustEmbedUnimplementedRoomServer()
}

// UnimplementedRoomServer must be embedded to have forward compatible implementations.
type UnimplementedRoomServer struct {
}

func (UnimplementedRoomServer) Get(context.Context, *RoomGetRequest) (*RoomGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRoomServer) GetByUserID(context.Context, *RoomGetByUserIDRequest) (*RoomGetByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserID not implemented")
}
func (UnimplementedRoomServer) GetUsers(context.Context, *RoomGetUsersRequest) (*RoomGetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedRoomServer) Create(context.Context, *RoomCreateRequest) (*RoomCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRoomServer) AddUser(context.Context, *RoomAddUserRequest) (*RoomAddUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedRoomServer) mustEmbedUnimplementedRoomServer() {}

// UnsafeRoomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomServer will
// result in compilation errors.
type UnsafeRoomServer interface {
	mustEmbedUnimplementedRoomServer()
}

func RegisterRoomServer(s grpc.ServiceRegistrar, srv RoomServer) {
	s.RegisterService(&_Room_serviceDesc, srv)
}

func _Room_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinfo.room.Room/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).Get(ctx, req.(*RoomGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_GetByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomGetByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).GetByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinfo.room.Room/GetByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).GetByUserID(ctx, req.(*RoomGetByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomGetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinfo.room.Room/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).GetUsers(ctx, req.(*RoomGetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinfo.room.Room/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).Create(ctx, req.(*RoomCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomAddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shinfo.room.Room/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).AddUser(ctx, req.(*RoomAddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Room_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shinfo.room.Room",
	HandlerType: (*RoomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Room_Get_Handler,
		},
		{
			MethodName: "GetByUserID",
			Handler:    _Room_GetByUserID_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _Room_GetUsers_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Room_Create_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _Room_AddUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/room/room.proto",
}
