// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.0
// source: internal/pb/room/room.proto

package room

import (
	proto "github.com/golang/protobuf/proto"
	pb "github.com/jklaw90/shinfo/internal/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RoomGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID string `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"` // required
}

func (x *RoomGetRequest) Reset() {
	*x = RoomGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_room_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetRequest) ProtoMessage() {}

func (x *RoomGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_room_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetRequest.ProtoReflect.Descriptor instead.
func (*RoomGetRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_room_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomGetRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type RoomGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *pb.Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *RoomGetResponse) Reset() {
	*x = RoomGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_room_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetResponse) ProtoMessage() {}

func (x *RoomGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_room_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetResponse.ProtoReflect.Descriptor instead.
func (*RoomGetResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_room_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomGetResponse) GetRoom() *pb.Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type RoomGetByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"` // required
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // required
	NextID string `protobuf:"bytes,3,opt,name=nextID,proto3" json:"nextID,omitempty"`
}

func (x *RoomGetByUserIDRequest) Reset() {
	*x = RoomGetByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_room_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomGetByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetByUserIDRequest) ProtoMessage() {}

func (x *RoomGetByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_room_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetByUserIDRequest.ProtoReflect.Descriptor instead.
func (*RoomGetByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_room_room_proto_rawDescGZIP(), []int{2}
}

func (x *RoomGetByUserIDRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RoomGetByUserIDRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RoomGetByUserIDRequest) GetNextID() string {
	if x != nil {
		return x.NextID
	}
	return ""
}

type RoomGetByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms  []*pb.UserRoom `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	NextID string         `protobuf:"bytes,2,opt,name=nextID,proto3" json:"nextID,omitempty"`
}

func (x *RoomGetByUserIDResponse) Reset() {
	*x = RoomGetByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_room_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomGetByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetByUserIDResponse) ProtoMessage() {}

func (x *RoomGetByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_room_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetByUserIDResponse.ProtoReflect.Descriptor instead.
func (*RoomGetByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_room_room_proto_rawDescGZIP(), []int{3}
}

func (x *RoomGetByUserIDResponse) GetRooms() []*pb.UserRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *RoomGetByUserIDResponse) GetNextID() string {
	if x != nil {
		return x.NextID
	}
	return ""
}

type RoomGetUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID string `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"` // required
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // required
	NextID string `protobuf:"bytes,3,opt,name=nextID,proto3" json:"nextID,omitempty"`
}

func (x *RoomGetUsersRequest) Reset() {
	*x = RoomGetUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_room_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomGetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetUsersRequest) ProtoMessage() {}

func (x *RoomGetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_room_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetUsersRequest.ProtoReflect.Descriptor instead.
func (*RoomGetUsersRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_room_room_proto_rawDescGZIP(), []int{4}
}

func (x *RoomGetUsersRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *RoomGetUsersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RoomGetUsersRequest) GetNextID() string {
	if x != nil {
		return x.NextID
	}
	return ""
}

type RoomGetUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users  []*pb.RoomUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextID string         `protobuf:"bytes,2,opt,name=nextID,proto3" json:"nextID,omitempty"`
}

func (x *RoomGetUsersResponse) Reset() {
	*x = RoomGetUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_room_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomGetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGetUsersResponse) ProtoMessage() {}

func (x *RoomGetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_room_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGetUsersResponse.ProtoReflect.Descriptor instead.
func (*RoomGetUsersResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_room_room_proto_rawDescGZIP(), []int{5}
}

func (x *RoomGetUsersResponse) GetUsers() []*pb.RoomUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *RoomGetUsersResponse) GetNextID() string {
	if x != nil {
		return x.NextID
	}
	return ""
}

type RoomCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     int64  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Public   bool   `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	Archived bool   `protobuf:"varint,4,opt,name=archived,proto3" json:"archived,omitempty"`
}

func (x *RoomCreateRequest) Reset() {
	*x = RoomCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_room_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateRequest) ProtoMessage() {}

func (x *RoomCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_room_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateRequest.ProtoReflect.Descriptor instead.
func (*RoomCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_room_room_proto_rawDescGZIP(), []int{6}
}

func (x *RoomCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomCreateRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RoomCreateRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *RoomCreateRequest) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type RoomCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *pb.Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *RoomCreateResponse) Reset() {
	*x = RoomCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_room_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateResponse) ProtoMessage() {}

func (x *RoomCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_room_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateResponse.ProtoReflect.Descriptor instead.
func (*RoomCreateResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_room_room_proto_rawDescGZIP(), []int{7}
}

func (x *RoomCreateResponse) GetRoom() *pb.Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type RoomAddUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID string   `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"` // required
	User   *pb.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`     // required
}

func (x *RoomAddUserRequest) Reset() {
	*x = RoomAddUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_room_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomAddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAddUserRequest) ProtoMessage() {}

func (x *RoomAddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_room_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAddUserRequest.ProtoReflect.Descriptor instead.
func (*RoomAddUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_room_room_proto_rawDescGZIP(), []int{8}
}

func (x *RoomAddUserRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *RoomAddUserRequest) GetUser() *pb.User {
	if x != nil {
		return x.User
	}
	return nil
}

type RoomAddUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoomAddUserResponse) Reset() {
	*x = RoomAddUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_room_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomAddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAddUserResponse) ProtoMessage() {}

func (x *RoomAddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_room_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAddUserResponse.ProtoReflect.Descriptor instead.
func (*RoomAddUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_room_room_proto_rawDescGZIP(), []int{9}
}

var File_internal_pb_room_room_proto protoreflect.FileDescriptor

var file_internal_pb_room_room_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x6f,
	0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73,
	0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x1a, 0x18, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0e, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x3a,
	0x0a, 0x0f, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x5e, 0x0a, 0x16, 0x52, 0x6f,
	0x6f, 0x6d, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x44, 0x22, 0x60, 0x0a, 0x17, 0x52, 0x6f,
	0x6f, 0x6d, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72,
	0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x44, 0x22, 0x5b, 0x0a, 0x13,
	0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x44, 0x22, 0x5d, 0x0a, 0x14, 0x52, 0x6f, 0x6f,
	0x6d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x44, 0x22, 0x6f, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x22, 0x3d, 0x0a, 0x12, 0x52, 0x6f, 0x6f,
	0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x27, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x55, 0x0a, 0x12, 0x52, 0x6f, 0x6f, 0x6d,
	0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x27, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x15, 0x0a, 0x13, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x96, 0x03, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12,
	0x42, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x23, 0x2e, 0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x51, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x20, 0x2e, 0x73, 0x68,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4b, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x73,
	0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73,
	0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4e, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x73, 0x68, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x64, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x68,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x64,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6b,
	0x6c, 0x61, 0x77, 0x39, 0x30, 0x2f, 0x73, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x3b, 0x72, 0x6f,
	0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_room_room_proto_rawDescOnce sync.Once
	file_internal_pb_room_room_proto_rawDescData = file_internal_pb_room_room_proto_rawDesc
)

func file_internal_pb_room_room_proto_rawDescGZIP() []byte {
	file_internal_pb_room_room_proto_rawDescOnce.Do(func() {
		file_internal_pb_room_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_room_room_proto_rawDescData)
	})
	return file_internal_pb_room_room_proto_rawDescData
}

var file_internal_pb_room_room_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_pb_room_room_proto_goTypes = []interface{}{
	(*RoomGetRequest)(nil),          // 0: shinfo.room.RoomGetRequest
	(*RoomGetResponse)(nil),         // 1: shinfo.room.RoomGetResponse
	(*RoomGetByUserIDRequest)(nil),  // 2: shinfo.room.RoomGetByUserIDRequest
	(*RoomGetByUserIDResponse)(nil), // 3: shinfo.room.RoomGetByUserIDResponse
	(*RoomGetUsersRequest)(nil),     // 4: shinfo.room.RoomGetUsersRequest
	(*RoomGetUsersResponse)(nil),    // 5: shinfo.room.RoomGetUsersResponse
	(*RoomCreateRequest)(nil),       // 6: shinfo.room.RoomCreateRequest
	(*RoomCreateResponse)(nil),      // 7: shinfo.room.RoomCreateResponse
	(*RoomAddUserRequest)(nil),      // 8: shinfo.room.RoomAddUserRequest
	(*RoomAddUserResponse)(nil),     // 9: shinfo.room.RoomAddUserResponse
	(*pb.Room)(nil),                 // 10: shinfo.common.Room
	(*pb.UserRoom)(nil),             // 11: shinfo.common.UserRoom
	(*pb.RoomUser)(nil),             // 12: shinfo.common.RoomUser
	(*pb.User)(nil),                 // 13: shinfo.common.User
}
var file_internal_pb_room_room_proto_depIdxs = []int32{
	10, // 0: shinfo.room.RoomGetResponse.room:type_name -> shinfo.common.Room
	11, // 1: shinfo.room.RoomGetByUserIDResponse.rooms:type_name -> shinfo.common.UserRoom
	12, // 2: shinfo.room.RoomGetUsersResponse.users:type_name -> shinfo.common.RoomUser
	10, // 3: shinfo.room.RoomCreateResponse.room:type_name -> shinfo.common.Room
	13, // 4: shinfo.room.RoomAddUserRequest.user:type_name -> shinfo.common.User
	0,  // 5: shinfo.room.Room.Get:input_type -> shinfo.room.RoomGetRequest
	2,  // 6: shinfo.room.Room.GetByUserID:input_type -> shinfo.room.RoomGetByUserIDRequest
	4,  // 7: shinfo.room.Room.GetUsers:input_type -> shinfo.room.RoomGetUsersRequest
	6,  // 8: shinfo.room.Room.Create:input_type -> shinfo.room.RoomCreateRequest
	8,  // 9: shinfo.room.Room.AddUser:input_type -> shinfo.room.RoomAddUserRequest
	1,  // 10: shinfo.room.Room.Get:output_type -> shinfo.room.RoomGetResponse
	3,  // 11: shinfo.room.Room.GetByUserID:output_type -> shinfo.room.RoomGetByUserIDResponse
	5,  // 12: shinfo.room.Room.GetUsers:output_type -> shinfo.room.RoomGetUsersResponse
	7,  // 13: shinfo.room.Room.Create:output_type -> shinfo.room.RoomCreateResponse
	9,  // 14: shinfo.room.Room.AddUser:output_type -> shinfo.room.RoomAddUserResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_pb_room_room_proto_init() }
func file_internal_pb_room_room_proto_init() {
	if File_internal_pb_room_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_room_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_room_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_room_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomGetByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_room_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomGetByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_room_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomGetUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_room_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomGetUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_room_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_room_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_room_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomAddUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_room_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomAddUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_room_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_room_room_proto_goTypes,
		DependencyIndexes: file_internal_pb_room_room_proto_depIdxs,
		MessageInfos:      file_internal_pb_room_room_proto_msgTypes,
	}.Build()
	File_internal_pb_room_room_proto = out.File
	file_internal_pb_room_room_proto_rawDesc = nil
	file_internal_pb_room_room_proto_goTypes = nil
	file_internal_pb_room_room_proto_depIdxs = nil
}
